apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-me-deploy
  labels:
    app: finance-me-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: finance-me-app
  template:
    metadata:
      labels:
        app: finance-me-app
    spec:
      containers:
      - name: finance-me-container
        image: ayath/finance-me-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: finance-me-np-service
  labels:
    app: finance-me-app
spec:
  selector:
    app: finance-me-app

  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8082
    targetPort: 8082
